name: 04-using-actions
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Printing the list
        run: ls
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app
    # checkout the code
    # install the dependencies
    # run the tests
