name: 2-workflow-event
on: workflow_dispatch

jobs:
  echo-event:
    runs-on: ubuntu-latest
    steps:
      - name: Shout Event Name
        run: echo "Event used to trigger me is ${{ github.event_name }}"